package com.irar.mores.handlers;

import com.irar.mores.crafting.AlloyCrafting;
import com.irar.mores.crafting.ToolCrafting;

import net.minecraft.init.Blocks;
import net.minecraft.init.Enchantments;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;

public class CraftingHandler {
	public static void init(){
		
		ItemStack EnchPickAikar = new ItemStack(ItemHandler.AikarPick);
		ItemStack EnchPickAoci = new ItemStack(ItemHandler.AociPick);
		ItemStack EnchPickAryxi = new ItemStack(ItemHandler.AryxiPick);
		ItemStack EnchPickAudu = new ItemStack(ItemHandler.AuduPick);
		ItemStack EnchPickBydoom = new ItemStack(ItemHandler.BydoomPick);
		ItemStack EnchPickDuxirete = new ItemStack(ItemHandler.DuxiretePick);
		ItemStack EnchPickIrine = new ItemStack(ItemHandler.IrinePick);
		ItemStack EnchPickJosawriline = new ItemStack(ItemHandler.JosawrilinePick);
		ItemStack EnchPickMurol = new ItemStack(ItemHandler.MurolPick);
		ItemStack EnchPickOdeznum = new ItemStack(ItemHandler.OdeznumPick);
		ItemStack EnchPickOivi = new ItemStack(ItemHandler.OiviPick);
		ItemStack EnchPickOivywon = new ItemStack(ItemHandler.OivywonPick);
		ItemStack EnchPickPetuxo = new ItemStack(ItemHandler.PetuxoPick);
		ItemStack EnchPickRo = new ItemStack(ItemHandler.RoPick);
		ItemStack EnchPickSusimen = new ItemStack(ItemHandler.SusimenPick);
		ItemStack EnchPickUamaf = new ItemStack(ItemHandler.UamafPick);
		ItemStack EnchPickUokuwixasi = new ItemStack(ItemHandler.UokuwixasiPick);
		ItemStack EnchPickVodricite = new ItemStack(ItemHandler.VodricitePick);
		ItemStack EnchPickVukanite = new ItemStack(ItemHandler.VukanitePick);
		ItemStack EnchPickZanine = new ItemStack(ItemHandler.ZaninePick);
		ItemStack EnchPickZawium = new ItemStack(ItemHandler.ZawiumPick);
		ItemStack EnchPickIsaxiwukou = new ItemStack(ItemHandler.IsaxiwukouPick);
		ItemStack EnchPickEninaz = new ItemStack(ItemHandler.EninazPick);
		ItemStack EnchPickEniri = new ItemStack(ItemHandler.EniriPick);
		ItemStack EnchPickIvio = new ItemStack(ItemHandler.IvioPick);
		ItemStack EnchPickEterixud = new ItemStack(ItemHandler.EterixudPick);
		ItemStack EnchPickNowyvio = new ItemStack(ItemHandler.NowyvioPick);
		ItemStack EnchShovelAikar = new ItemStack(ItemHandler.AikarPick);
		ItemStack EnchShovelAoci = new ItemStack(ItemHandler.AociPick);
		ItemStack EnchShovelAryxi = new ItemStack(ItemHandler.AryxiPick);
		ItemStack EnchShovelAudu = new ItemStack(ItemHandler.AuduPick);
		ItemStack EnchShovelBydoom = new ItemStack(ItemHandler.BydoomPick);
		ItemStack EnchShovelDuxirete = new ItemStack(ItemHandler.DuxireteShovel);
		ItemStack EnchShovelIrine = new ItemStack(ItemHandler.IrineShovel);
		ItemStack EnchShovelJosawriline = new ItemStack(ItemHandler.JosawrilineShovel);
		ItemStack EnchShovelMurol = new ItemStack(ItemHandler.MurolShovel);
		ItemStack EnchShovelOdeznum = new ItemStack(ItemHandler.OdeznumShovel);
		ItemStack EnchShovelOivi = new ItemStack(ItemHandler.OiviShovel);
		ItemStack EnchShovelOivywon = new ItemStack(ItemHandler.OivywonShovel);
		ItemStack EnchShovelPetuxo = new ItemStack(ItemHandler.PetuxoShovel);
		ItemStack EnchShovelRo = new ItemStack(ItemHandler.RoShovel);
		ItemStack EnchShovelSusimen = new ItemStack(ItemHandler.SusimenShovel);
		ItemStack EnchShovelUamaf = new ItemStack(ItemHandler.UamafShovel);
		ItemStack EnchShovelUokuwixasi = new ItemStack(ItemHandler.UokuwixasiShovel);
		ItemStack EnchShovelVodricite = new ItemStack(ItemHandler.VodriciteShovel);
		ItemStack EnchShovelVukanite = new ItemStack(ItemHandler.VukaniteShovel);
		ItemStack EnchShovelZanine = new ItemStack(ItemHandler.ZanineShovel);
		ItemStack EnchShovelZawium = new ItemStack(ItemHandler.ZawiumShovel);
		ItemStack EnchShovelIsaxiwukou = new ItemStack(ItemHandler.IsaxiwukouShovel);
		ItemStack EnchShovelEninaz = new ItemStack(ItemHandler.EninazShovel);
		ItemStack EnchShovelEniri = new ItemStack(ItemHandler.EniriShovel);
		ItemStack EnchShovelIvio = new ItemStack(ItemHandler.IvioShovel);
		ItemStack EnchShovelEterixud = new ItemStack(ItemHandler.EterixudShovel);
		ItemStack EnchShovelNowyvio = new ItemStack(ItemHandler.NowyvioShovel);
		ItemStack EnchAxeAikar = new ItemStack(ItemHandler.AikarAxe);
		ItemStack EnchAxeAoci = new ItemStack(ItemHandler.AociAxe);
		ItemStack EnchAxeAryxi = new ItemStack(ItemHandler.AryxiAxe);
		ItemStack EnchAxeAudu = new ItemStack(ItemHandler.AuduAxe);
		ItemStack EnchAxeBydoom = new ItemStack(ItemHandler.BydoomAxe);
		ItemStack EnchAxeDuxirete = new ItemStack(ItemHandler.DuxireteAxe);
		ItemStack EnchAxeIrine = new ItemStack(ItemHandler.IrineAxe);
		ItemStack EnchAxeJosawriline = new ItemStack(ItemHandler.JosawrilineAxe);
		ItemStack EnchAxeMurol = new ItemStack(ItemHandler.MurolAxe);
		ItemStack EnchAxeOdeznum = new ItemStack(ItemHandler.OdeznumAxe);
		ItemStack EnchAxeOivi = new ItemStack(ItemHandler.OiviAxe);
		ItemStack EnchAxeOivywon = new ItemStack(ItemHandler.OivywonAxe);
		ItemStack EnchAxePetuxo = new ItemStack(ItemHandler.PetuxoAxe);
		ItemStack EnchAxeRo = new ItemStack(ItemHandler.RoAxe);
		ItemStack EnchAxeSusimen = new ItemStack(ItemHandler.SusimenAxe);
		ItemStack EnchAxeUamaf = new ItemStack(ItemHandler.UamafAxe);
		ItemStack EnchAxeUokuwixasi = new ItemStack(ItemHandler.UokuwixasiAxe);
		ItemStack EnchAxeVodricite = new ItemStack(ItemHandler.VodriciteAxe);
		ItemStack EnchAxeVukanite = new ItemStack(ItemHandler.VukaniteAxe);
		ItemStack EnchAxeZanine = new ItemStack(ItemHandler.ZanineAxe);
		ItemStack EnchAxeZawium = new ItemStack(ItemHandler.ZawiumAxe);
		ItemStack EnchAxeIsaxiwukou = new ItemStack(ItemHandler.IsaxiwukouAxe);
		ItemStack EnchAxeEninaz = new ItemStack(ItemHandler.EninazAxe);
		ItemStack EnchAxeEniri = new ItemStack(ItemHandler.EniriAxe);
		ItemStack EnchAxeIvio = new ItemStack(ItemHandler.IvioAxe);
		ItemStack EnchAxeEterixud = new ItemStack(ItemHandler.EterixudAxe);
		ItemStack EnchAxeNowyvio = new ItemStack(ItemHandler.NowyvioAxe);
		ItemStack EnchSwordAikar = new ItemStack(ItemHandler.AikarSword);
		ItemStack EnchSwordAoci = new ItemStack(ItemHandler.AociSword);
		ItemStack EnchSwordAryxi = new ItemStack(ItemHandler.AryxiSword);
		ItemStack EnchSwordAudu = new ItemStack(ItemHandler.AuduSword);
		ItemStack EnchSwordBydoom = new ItemStack(ItemHandler.BydoomSword);
		ItemStack EnchSwordDuxirete = new ItemStack(ItemHandler.DuxireteSword);
		ItemStack EnchSwordIrine = new ItemStack(ItemHandler.IrineSword);
		ItemStack EnchSwordJosawriline = new ItemStack(ItemHandler.JosawrilineSword);
		ItemStack EnchSwordMurol = new ItemStack(ItemHandler.MurolSword);
		ItemStack EnchSwordOdeznum = new ItemStack(ItemHandler.OdeznumSword);
		ItemStack EnchSwordOivi = new ItemStack(ItemHandler.OiviSword);
		ItemStack EnchSwordOivywon = new ItemStack(ItemHandler.OivywonSword);
		ItemStack EnchSwordPetuxo = new ItemStack(ItemHandler.PetuxoSword);
		ItemStack EnchSwordRo = new ItemStack(ItemHandler.RoSword);
		ItemStack EnchSwordSusimen = new ItemStack(ItemHandler.SusimenSword);
		ItemStack EnchSwordUamaf = new ItemStack(ItemHandler.UamafSword);
		ItemStack EnchSwordUokuwixasi = new ItemStack(ItemHandler.UokuwixasiSword);
		ItemStack EnchSwordVodricite = new ItemStack(ItemHandler.VodriciteSword);
		ItemStack EnchSwordVukanite = new ItemStack(ItemHandler.VukaniteSword);
		ItemStack EnchSwordZanine = new ItemStack(ItemHandler.ZanineSword);
		ItemStack EnchSwordZawium = new ItemStack(ItemHandler.ZawiumSword);
		ItemStack EnchSwordIsaxiwukou = new ItemStack(ItemHandler.IsaxiwukouSword);
		ItemStack EnchSwordEninaz = new ItemStack(ItemHandler.EninazSword);
		ItemStack EnchSwordEniri = new ItemStack(ItemHandler.EniriSword);
		ItemStack EnchSwordIvio = new ItemStack(ItemHandler.IvioSword);
		ItemStack EnchSwordEterixud = new ItemStack(ItemHandler.EterixudSword);
		ItemStack EnchSwordNowyvio = new ItemStack(ItemHandler.NowyvioSword);
		
		
		EnchSwordAikar.addEnchantment(Enchantments.SHARPNESS, 3);
		EnchAxeAikar.addEnchantment(Enchantments.SHARPNESS, 3);
		EnchSwordAoci.addEnchantment(Enchantments.SHARPNESS, 2);
		EnchAxeAoci.addEnchantment(Enchantments.SHARPNESS, 2);
		EnchPickAryxi.addEnchantment(Enchantments.EFFICIENCY, 4);
		EnchShovelAryxi.addEnchantment(Enchantments.EFFICIENCY, 4);
		EnchAxeAryxi.addEnchantment(Enchantments.EFFICIENCY, 4);
		EnchSwordAudu.addEnchantment(Enchantments.SHARPNESS, 4);
		EnchAxeAudu.addEnchantment(Enchantments.SHARPNESS, 4);
		EnchSwordDuxirete.addEnchantment(Enchantments.SHARPNESS, 5);
		EnchAxeDuxirete.addEnchantment(Enchantments.SHARPNESS, 5);
		EnchPickIrine.addEnchantment(Enchantments.FORTUNE, 3);
		EnchShovelIrine.addEnchantment(Enchantments.FORTUNE, 3);
		EnchAxeIrine.addEnchantment(Enchantments.FORTUNE, 3);
		EnchSwordIrine.addEnchantment(Enchantments.LOOTING, 3);
		EnchPickJosawriline.addEnchantment(Enchantments.EFFICIENCY, 3);
		EnchShovelJosawriline.addEnchantment(Enchantments.EFFICIENCY, 3);
		EnchAxeJosawriline.addEnchantment(Enchantments.EFFICIENCY, 3);
		EnchPickOivywon.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchShovelOivywon.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchAxeOivywon.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchPickOivywon.addEnchantment(Enchantments.UNBREAKING, 3);
		EnchShovelOivywon.addEnchantment(Enchantments.UNBREAKING, 3);
		EnchAxeOivywon.addEnchantment(Enchantments.UNBREAKING, 3);
		EnchSwordOivywon.addEnchantment(Enchantments.UNBREAKING, 3);
		EnchPickPetuxo.addEnchantment(Enchantments.EFFICIENCY, 5);
		EnchShovelPetuxo.addEnchantment(Enchantments.EFFICIENCY, 5);
		EnchAxePetuxo.addEnchantment(Enchantments.EFFICIENCY, 5);
		EnchPickRo.addEnchantment(Enchantments.EFFICIENCY, 2);
		EnchShovelRo.addEnchantment(Enchantments.EFFICIENCY, 2);
		EnchAxeRo.addEnchantment(Enchantments.EFFICIENCY, 2);
		EnchSwordSusimen.addEnchantment(Enchantments.SHARPNESS, 1);
		EnchAxeSusimen.addEnchantment(Enchantments.SHARPNESS, 1);
		EnchPickUamaf.addEnchantment(Enchantments.EFFICIENCY, 1);
		EnchShovelUamaf.addEnchantment(Enchantments.EFFICIENCY, 1);
		EnchAxeUamaf.addEnchantment(Enchantments.EFFICIENCY, 1);
		EnchPickUokuwixasi.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchShovelUokuwixasi.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchAxeUokuwixasi.addEnchantment(Enchantments.SILK_TOUCH, 1);
		EnchPickVodricite.addEnchantment(Enchantments.FORTUNE, 1);
		EnchShovelVodricite.addEnchantment(Enchantments.FORTUNE, 1);
		EnchAxeVodricite.addEnchantment(Enchantments.FORTUNE, 1);
		EnchSwordVodricite.addEnchantment(Enchantments.LOOTING, 1);
		EnchPickVukanite.addEnchantment(Enchantments.FORTUNE, 2);
		EnchShovelVukanite.addEnchantment(Enchantments.FORTUNE, 2);
		EnchAxeVukanite.addEnchantment(Enchantments.FORTUNE, 2);
		EnchSwordVukanite.addEnchantment(Enchantments.LOOTING, 2);
		EnchPickZanine.addEnchantment(Enchantments.UNBREAKING, 2);
		EnchShovelZanine.addEnchantment(Enchantments.UNBREAKING, 2);
		EnchAxeZanine.addEnchantment(Enchantments.UNBREAKING, 2);
		EnchSwordZanine.addEnchantment(Enchantments.UNBREAKING, 2);
		EnchPickZawium.addEnchantment(Enchantments.UNBREAKING, 1);
		EnchShovelZawium.addEnchantment(Enchantments.UNBREAKING, 1);
		EnchAxeZawium.addEnchantment(Enchantments.UNBREAKING, 1);
		EnchSwordZawium.addEnchantment(Enchantments.UNBREAKING, 1);
		EnchSwordIsaxiwukou.addEnchantment(Enchantments.LOOTING, 5);
		EnchPickEninaz.addEnchantment(Enchantments.UNBREAKING, 4);
		EnchShovelEninaz.addEnchantment(Enchantments.UNBREAKING, 4);
		EnchAxeEninaz.addEnchantment(Enchantments.UNBREAKING, 4);
		EnchSwordEninaz.addEnchantment(Enchantments.UNBREAKING, 4);
		EnchPickEniri.addEnchantment(Enchantments.FORTUNE, 4);
		EnchShovelEniri.addEnchantment(Enchantments.FORTUNE, 4);
		EnchAxeEniri.addEnchantment(Enchantments.FORTUNE, 4);
		EnchSwordIvio.addEnchantment(Enchantments.LOOTING, 4);
		EnchSwordEterixud.addEnchantment(Enchantments.SHARPNESS, 7);
		EnchAxeEterixud.addEnchantment(Enchantments.SHARPNESS, 7);
		EnchPickNowyvio.addEnchantment(Enchantments.EFFICIENCY, 7);
		EnchShovelNowyvio.addEnchantment(Enchantments.EFFICIENCY, 7);
		EnchAxeNowyvio.addEnchantment(Enchantments.EFFICIENCY, 7);
		
		
		
		ForgeRegistries.RECIPES.register(new AlloyCrafting());
		ForgeRegistries.RECIPES.register(new ToolCrafting(new int[] {0, 1, 2}, new int[] {4, 7}, ItemHandler.AlloyPickaxe));
		ForgeRegistries.RECIPES.register(new ToolCrafting(new int[] {1}, new int[] {4, 7}, ItemHandler.AlloyShovel));
		ForgeRegistries.RECIPES.register(new ToolCrafting(new int[] {1, 2, 5}, new int[] {4, 7}, ItemHandler.AlloyAxe));
		ForgeRegistries.RECIPES.register(new ToolCrafting(new int[] {0, 1, 3}, new int[] {4, 7}, ItemHandler.AlloyAxe));
		
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ph_ore"), new ResourceLocation("custom_recipes"), new ItemStack(BlockHandler.PhantomOre), new Object[]{"PP", "PP", 'P', ItemHandler.PhantomShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ph_ore2"), new ResourceLocation("custom_recipes"), new ItemStack(BlockHandler.NetherPhantomOre), new Object[]{" P ", "PNP", " P ", 'P', ItemHandler.PhantomShard, 'N', Blocks.NETHERRACK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_sh"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.BlackHoleShard), new Object[]{"PP", "PP", 'P', ItemHandler.BlackHoleFragment});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in1"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.IsaxiwukouIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.UokuwixasiIngot, 'S', ItemHandler.BlackHoleShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in2"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.EninazIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.ZanineIngot, 'S', ItemHandler.BlackHoleShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in3"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.EniriIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.IrineIngot, 'S', ItemHandler.BlackHoleShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in4"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.IvioIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.OiviIngot, 'S', ItemHandler.BlackHoleShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in5"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.EterixudIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.DuxireteIngot, 'S', ItemHandler.BlackHoleShard});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:bh_in6"), new ResourceLocation("custom_recipes"), new ItemStack(ItemHandler.NowyvioIngot, 4), new Object[]{" I ", "ISI", " I ", 'I', ItemHandler.OivywonIngot, 'S', ItemHandler.BlackHoleShard});
		
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ai_pick"), new ResourceLocation("custom_recipes"), EnchPickAikar, new Object[]{"III", " S ", " S ", 'I', "ingotAikar", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ao_pick"), new ResourceLocation("custom_recipes"), EnchPickAoci, new Object[]{"III", " S ", " S ", 'I', "ingotAoci", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ar_pick"), new ResourceLocation("custom_recipes"), EnchPickAryxi, new Object[]{"III", " S ", " S ", 'I', "ingotAryxi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:au_pick"), new ResourceLocation("custom_recipes"), EnchPickAudu, new Object[]{"III", " S ", " S ", 'I', "ingotAudu", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:by_pick"), new ResourceLocation("custom_recipes"), EnchPickBydoom, new Object[]{"III", " S ", " S ", 'I', "ingotBydoom", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:du_pick"), new ResourceLocation("custom_recipes"), EnchPickDuxirete, new Object[]{"III", " S ", " S ", 'I', "ingotDuxirete", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ir_pick"), new ResourceLocation("custom_recipes"), EnchPickIrine, new Object[]{"III", " S ", " S ", 'I', "ingotIrine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:jo_pick"), new ResourceLocation("custom_recipes"), EnchPickJosawriline, new Object[]{"III", " S ", " S ", 'I', "ingotJosawriline", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:mu_pick"), new ResourceLocation("custom_recipes"), EnchPickMurol, new Object[]{"III", " S ", " S ", 'I', "ingotMurol", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:od_pick"), new ResourceLocation("custom_recipes"), EnchPickOdeznum, new Object[]{"III", " S ", " S ", 'I', "ingotOdeznum", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oi_pick"), new ResourceLocation("custom_recipes"), EnchPickOivi, new Object[]{"III", " S ", " S ", 'I', "ingotOivi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oy_pick"), new ResourceLocation("custom_recipes"), EnchPickOivywon, new Object[]{"III", " S ", " S ", 'I', "ingotOivywon", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:pe_pick"), new ResourceLocation("custom_recipes"), EnchPickPetuxo, new Object[]{"III", " S ", " S ", 'I', "ingotPetuxo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ro_pick"), new ResourceLocation("custom_recipes"), EnchPickRo, new Object[]{"III", " S ", " S ", 'I', "ingotRo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:su_pick"), new ResourceLocation("custom_recipes"), EnchPickSusimen, new Object[]{"III", " S ", " S ", 'I', "ingotSusimen", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ua_pick"), new ResourceLocation("custom_recipes"), EnchPickUamaf, new Object[]{"III", " S ", " S ", 'I', "ingotUamaf", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:uo_pick"), new ResourceLocation("custom_recipes"), EnchPickUokuwixasi, new Object[]{"III", " S ", " S ", 'I', "ingotUokuwixasi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vo_pick"), new ResourceLocation("custom_recipes"), EnchPickVodricite, new Object[]{"III", " S ", " S ", 'I', "ingotVodricite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vu_pick"), new ResourceLocation("custom_recipes"), EnchPickVukanite, new Object[]{"III", " S ", " S ", 'I', "ingotVukanite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:za_pick"), new ResourceLocation("custom_recipes"), EnchPickZanine, new Object[]{"III", " S ", " S ", 'I', "ingotZanine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:zw_pick"), new ResourceLocation("custom_recipes"), EnchPickZawium, new Object[]{"III", " S ", " S ", 'I', "ingotZawium", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:is_pick"), new ResourceLocation("custom_recipes"), EnchPickIsaxiwukou, new Object[]{"III", " S ", " S ", 'I', "ingotIsaxiwukou", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:en_pick"), new ResourceLocation("custom_recipes"), EnchPickEninaz, new Object[]{"III", " S ", " S ", 'I', "ingotEninaz", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ei_pick"), new ResourceLocation("custom_recipes"), EnchPickEniri, new Object[]{"III", " S ", " S ", 'I', "ingotEniri", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:iv_pick"), new ResourceLocation("custom_recipes"), EnchPickIvio, new Object[]{"III", " S ", " S ", 'I', "ingotIvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:et_pick"), new ResourceLocation("custom_recipes"), EnchPickEterixud, new Object[]{"III", " S ", " S ", 'I', "ingotEterixud", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:no_pick"), new ResourceLocation("custom_recipes"), EnchPickNowyvio, new Object[]{"III", " S ", " S ", 'I', "ingotNowyvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ai_shovel"), new ResourceLocation("custom_recipes"), EnchShovelAikar, new Object[]{" I ", " S ", " S ", 'I', "ingotAikar", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ao_shovel"), new ResourceLocation("custom_recipes"), EnchShovelAoci, new Object[]{" I ", " S ", " S ", 'I', "ingotAoci", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ar_shovel"), new ResourceLocation("custom_recipes"), EnchShovelAryxi, new Object[]{" I ", " S ", " S ", 'I', "ingotAryxi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:au_shovel"), new ResourceLocation("custom_recipes"), EnchShovelAudu, new Object[]{" I ", " S ", " S ", 'I', "ingotAudu", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:by_shovel"), new ResourceLocation("custom_recipes"), EnchShovelBydoom, new Object[]{" I ", " S ", " S ", 'I', "ingotBydoom", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:du_shovel"), new ResourceLocation("custom_recipes"), EnchShovelDuxirete, new Object[]{" I ", " S ", " S ", 'I', "ingotDuxirete", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ir_shovel"), new ResourceLocation("custom_recipes"), EnchShovelIrine, new Object[]{" I ", " S ", " S ", 'I', "ingotIrine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:jo_shovel"), new ResourceLocation("custom_recipes"), EnchShovelJosawriline, new Object[]{" I ", " S ", " S ", 'I', "ingotJosawriline", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:mu_shovel"), new ResourceLocation("custom_recipes"), EnchShovelMurol, new Object[]{" I ", " S ", " S ", 'I', "ingotMurol", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:od_shovel"), new ResourceLocation("custom_recipes"), EnchShovelOdeznum, new Object[]{" I ", " S ", " S ", 'I', "ingotOdeznum", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oi_shovel"), new ResourceLocation("custom_recipes"), EnchShovelOivi, new Object[]{" I ", " S ", " S ", 'I', "ingotOivi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oy_shovel"), new ResourceLocation("custom_recipes"), EnchShovelOivywon, new Object[]{" I ", " S ", " S ", 'I', "ingotOivywon", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:pe_shovel"), new ResourceLocation("custom_recipes"), EnchShovelPetuxo, new Object[]{" I ", " S ", " S ", 'I', "ingotPetuxo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ro_shovel"), new ResourceLocation("custom_recipes"), EnchShovelRo, new Object[]{" I ", " S ", " S ", 'I', "ingotRo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:su_shovel"), new ResourceLocation("custom_recipes"), EnchShovelSusimen, new Object[]{" I ", " S ", " S ", 'I', "ingotSusimen", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ua_shovel"), new ResourceLocation("custom_recipes"), EnchShovelUamaf, new Object[]{" I ", " S ", " S ", 'I', "ingotUamaf", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:uo_shovel"), new ResourceLocation("custom_recipes"), EnchShovelUokuwixasi, new Object[]{" I ", " S ", " S ", 'I', "ingotUokuwixasi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vo_shovel"), new ResourceLocation("custom_recipes"), EnchShovelVodricite, new Object[]{" I ", " S ", " S ", 'I', "ingotVodricite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vu_shovel"), new ResourceLocation("custom_recipes"), EnchShovelVukanite, new Object[]{" I ", " S ", " S ", 'I', "ingotVukanite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:za_shovel"), new ResourceLocation("custom_recipes"), EnchShovelZanine, new Object[]{" I ", " S ", " S ", 'I', "ingotZanine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:zw_shovel"), new ResourceLocation("custom_recipes"), EnchShovelZawium, new Object[]{" I ", " S ", " S ", 'I', "ingotZawium", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:is_shovel"), new ResourceLocation("custom_recipes"), EnchShovelIsaxiwukou, new Object[]{" I ", " S ", " S ", 'I', "ingotIsaxiwukou", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:en_shovel"), new ResourceLocation("custom_recipes"), EnchShovelEninaz, new Object[]{" I ", " S ", " S ", 'I', "ingotEninaz", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ei_shovel"), new ResourceLocation("custom_recipes"), EnchShovelEniri, new Object[]{" I ", " S ", " S ", 'I', "ingotEniri", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:iv_shovel"), new ResourceLocation("custom_recipes"), EnchShovelIvio, new Object[]{" I ", " S ", " S ", 'I', "ingotIvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:et_shovel"), new ResourceLocation("custom_recipes"), EnchShovelEterixud, new Object[]{" I ", " S ", " S ", 'I', "ingotEterixud", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:no_shovel"), new ResourceLocation("custom_recipes"), EnchShovelNowyvio, new Object[]{" I ", " S ", " S ", 'I', "ingotNowyvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ai_axe"), new ResourceLocation("custom_recipes"), EnchAxeAikar, new Object[]{" II", " SI", " S ", 'I', "ingotAikar", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ao_axe"), new ResourceLocation("custom_recipes"), EnchAxeAoci, new Object[]{" II", " SI", " S ", 'I', "ingotAoci", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ar_axe"), new ResourceLocation("custom_recipes"), EnchAxeAryxi, new Object[]{" II", " SI", " S ", 'I', "ingotAryxi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:au_axe"), new ResourceLocation("custom_recipes"), EnchAxeAudu, new Object[]{" II", " SI", " S ", 'I', "ingotAudu", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:by_axe"), new ResourceLocation("custom_recipes"), EnchAxeBydoom, new Object[]{" II", " SI", " S ", 'I', "ingotBydoom", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:du_axe"), new ResourceLocation("custom_recipes"), EnchAxeDuxirete, new Object[]{" II", " SI", " S ", 'I', "ingotDuxirete", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ir_axe"), new ResourceLocation("custom_recipes"), EnchAxeIrine, new Object[]{" II", " SI", " S ", 'I', "ingotIrine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:jo_axe"), new ResourceLocation("custom_recipes"), EnchAxeJosawriline, new Object[]{" II", " SI", " S ", 'I', "ingotJosawriline", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:mu_axe"), new ResourceLocation("custom_recipes"), EnchAxeMurol, new Object[]{" II", " SI", " S ", 'I', "ingotMurol", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:od_axe"), new ResourceLocation("custom_recipes"), EnchAxeOdeznum, new Object[]{" II", " SI", " S ", 'I', "ingotOdeznum", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oi_axe"), new ResourceLocation("custom_recipes"), EnchAxeOivi, new Object[]{" II", " SI", " S ", 'I', "ingotOivi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oy_axe"), new ResourceLocation("custom_recipes"), EnchAxeOivywon, new Object[]{" II", " SI", " S ", 'I', "ingotOivywon", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:pe_axe"), new ResourceLocation("custom_recipes"), EnchAxePetuxo, new Object[]{" II", " SI", " S ", 'I', "ingotPetuxo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ro_axe"), new ResourceLocation("custom_recipes"), EnchAxeRo, new Object[]{" II", " SI", " S ", 'I', "ingotRo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:su_axe"), new ResourceLocation("custom_recipes"), EnchAxeSusimen, new Object[]{" II", " SI", " S ", 'I', "ingotSusimen", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ua_axe"), new ResourceLocation("custom_recipes"), EnchAxeUamaf, new Object[]{" II", " SI", " S ", 'I', "ingotUamaf", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:uo_axe"), new ResourceLocation("custom_recipes"), EnchAxeUokuwixasi, new Object[]{" II", " SI", " S ", 'I', "ingotUokuwixasi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vo_axe"), new ResourceLocation("custom_recipes"), EnchAxeVodricite, new Object[]{" II", " SI", " S ", 'I', "ingotVodricite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vu_axe"), new ResourceLocation("custom_recipes"), EnchAxeVukanite, new Object[]{" II", " SI", " S ", 'I', "ingotVukanite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:za_axe"), new ResourceLocation("custom_recipes"), EnchAxeZanine, new Object[]{" II", " SI", " S ", 'I', "ingotZanine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:zw_axe"), new ResourceLocation("custom_recipes"), EnchAxeZawium, new Object[]{" II", " SI", " S ", 'I', "ingotZawium", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:is_axe"), new ResourceLocation("custom_recipes"), EnchAxeIsaxiwukou, new Object[]{" II", " SI", " S ", 'I', "ingotIsaxiwukou", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:en_axe"), new ResourceLocation("custom_recipes"), EnchAxeEninaz, new Object[]{" II", " SI", " S ", 'I', "ingotEninaz", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ei_axe"), new ResourceLocation("custom_recipes"), EnchAxeEniri, new Object[]{" II", " SI", " S ", 'I', "ingotEniri", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:iv_axe"), new ResourceLocation("custom_recipes"), EnchAxeIvio, new Object[]{" II", " SI", " S ", 'I', "ingotIvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:et_axe"), new ResourceLocation("custom_recipes"), EnchAxeEterixud, new Object[]{" II", " SI", " S ", 'I', "ingotEterixud", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:no_axe"), new ResourceLocation("custom_recipes"), EnchAxeNowyvio, new Object[]{" II", " SI", " S ", 'I', "ingotNowyvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ai_sword"), new ResourceLocation("custom_recipes"), EnchSwordAikar, new Object[]{" I ", " I ", " S ", 'I', "ingotAikar", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ao_sword"), new ResourceLocation("custom_recipes"), EnchSwordAoci, new Object[]{" I ", " I ", " S ", 'I', "ingotAoci", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ar_sword"), new ResourceLocation("custom_recipes"), EnchSwordAryxi, new Object[]{" I ", " I ", " S ", 'I', "ingotAryxi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:au_sword"), new ResourceLocation("custom_recipes"), EnchSwordAudu, new Object[]{" I ", " I ", " S ", 'I', "ingotAudu", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:by_sword"), new ResourceLocation("custom_recipes"), EnchSwordBydoom, new Object[]{" I ", " I ", " S ", 'I', ItemHandler.BydoomIngot, 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:du_sword"), new ResourceLocation("custom_recipes"), EnchSwordDuxirete, new Object[]{" I ", " I ", " S ", 'I', "ingotDuxirete", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ir_sword"), new ResourceLocation("custom_recipes"), EnchSwordIrine, new Object[]{" I ", " I ", " S ", 'I', "ingotIrine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:jo_sword"), new ResourceLocation("custom_recipes"), EnchSwordJosawriline, new Object[]{" I ", " I ", " S ", 'I', "ingotJosawriline", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:mu_sword"), new ResourceLocation("custom_recipes"), EnchSwordMurol, new Object[]{" I ", " I ", " S ", 'I', "ingotMurol", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:od_sword"), new ResourceLocation("custom_recipes"), EnchSwordOdeznum, new Object[]{" I ", " I ", " S ", 'I', "ingotOdeznum", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oi_sword"), new ResourceLocation("custom_recipes"), EnchSwordOivi, new Object[]{" I ", " I ", " S ", 'I', "ingotOivi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:oy_sword"), new ResourceLocation("custom_recipes"), EnchSwordOivywon, new Object[]{" I ", " I ", " S ", 'I', "ingotOivywon", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:pe_sword"), new ResourceLocation("custom_recipes"), EnchSwordPetuxo, new Object[]{" I ", " I ", " S ", 'I', "ingotPetuxo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ro_sword"), new ResourceLocation("custom_recipes"), EnchSwordRo, new Object[]{" I ", " I ", " S ", 'I', "ingotRo", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:su_sword"), new ResourceLocation("custom_recipes"), EnchSwordSusimen, new Object[]{" I ", " I ", " S ", 'I', "ingotSusimen", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ua_sword"), new ResourceLocation("custom_recipes"), EnchSwordUamaf, new Object[]{" I ", " I ", " S ", 'I', "ingotUamaf", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:uo_sword"), new ResourceLocation("custom_recipes"), EnchSwordUokuwixasi, new Object[]{" I ", " I ", " S ", 'I', "ingotUokuwixasi", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vo_sword"), new ResourceLocation("custom_recipes"), EnchSwordVodricite, new Object[]{" I ", " I ", " S ", 'I', "ingotVodricite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:vu_sword"), new ResourceLocation("custom_recipes"), EnchSwordVukanite, new Object[]{" I ", " I ", " S ", 'I', "ingotVukanite", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:za_sword"), new ResourceLocation("custom_recipes"), EnchSwordZanine, new Object[]{" I ", " I ", " S ", 'I', "ingotZanine", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:zw_sword"), new ResourceLocation("custom_recipes"), EnchSwordZawium, new Object[]{" I ", " I ", " S ", 'I', "ingotZawium", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:is_sword"), new ResourceLocation("custom_recipes"), EnchSwordIsaxiwukou, new Object[]{" I ", " I ", " S ", 'I', "ingotIsaxiwukou", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:en_sword"), new ResourceLocation("custom_recipes"), EnchSwordEninaz, new Object[]{" I ", " I ", " S ", 'I', "ingotEninaz", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:ei_sword"), new ResourceLocation("custom_recipes"), EnchSwordEniri, new Object[]{" I ", " I ", " S ", 'I', "ingotEniri", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:iv_sword"), new ResourceLocation("custom_recipes"), EnchSwordIvio, new Object[]{" I ", " I ", " S ", 'I', "ingotIvio", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:et_sword"), new ResourceLocation("custom_recipes"), EnchSwordEterixud, new Object[]{" I ", " I ", " S ", 'I', "ingotEterixud", 'S', Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("mores:no_sword"), new ResourceLocation("custom_recipes"), EnchSwordNowyvio, new Object[]{" I ", " I ", " S ", 'I', "ingotNowyvio", 'S', Items.STICK});
		
		
		GameRegistry.addSmelting(ItemHandler.AikarDust, new ItemStack(ItemHandler.AikarIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.AociDust, new ItemStack(ItemHandler.AociIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.AryxiDust, new ItemStack(ItemHandler.AryxiIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.AuduDust, new ItemStack(ItemHandler.AuduIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.BydoomDust, new ItemStack(ItemHandler.BydoomIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.DuxireteDust, new ItemStack(ItemHandler.DuxireteIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.IrineDust, new ItemStack(ItemHandler.IrineIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.JosawrilineDust, new ItemStack(ItemHandler.JosawrilineIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.MurolDust, new ItemStack(ItemHandler.MurolIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.OdeznumDust, new ItemStack(ItemHandler.OdeznumIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.OiviDust, new ItemStack(ItemHandler.OiviIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.OivywonDust, new ItemStack(ItemHandler.OivywonIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.PetuxoDust, new ItemStack(ItemHandler.PetuxoIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.RoDust, new ItemStack(ItemHandler.RoIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.SusimenDust, new ItemStack(ItemHandler.SusimenIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.UamafDust, new ItemStack(ItemHandler.UamafIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.UokuwixasiDust, new ItemStack(ItemHandler.UokuwixasiIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.VodriciteDust, new ItemStack(ItemHandler.VodriciteIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.VukaniteDust, new ItemStack(ItemHandler.VukaniteIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.ZanineDust, new ItemStack(ItemHandler.ZanineIngot), 1.0F);
		GameRegistry.addSmelting(ItemHandler.ZawiumDust, new ItemStack(ItemHandler.ZawiumIngot), 1.0F);
		GameRegistry.addSmelting(BlockHandler.BlackHoleOre, new ItemStack(ItemHandler.BlackHoleFragment, 2), 10.0F);
		
		
		if(Loader.isModLoaded("iron")){
			ItemStack EnchSwordDetriminium = new ItemStack(ItemHandler.DetriminiumSword);
			ItemStack EnchPickDetriminium = new ItemStack(ItemHandler.DetriminiumPick);
			ItemStack EnchShovelDetriminium = new ItemStack(ItemHandler.DetriminiumShovel);
			ItemStack EnchAxeDetriminium = new ItemStack(ItemHandler.DetriminiumAxe);
			
			EnchSwordDetriminium.addEnchantment(Enchantments.FIRE_ASPECT, 50);
			EnchSwordDetriminium.addEnchantment(Enchantments.KNOCKBACK, 50);
			EnchSwordDetriminium.addEnchantment(Enchantments.LOOTING, 50);
			EnchSwordDetriminium.addEnchantment(Enchantments.SHARPNESS, 50);
			EnchSwordDetriminium.addEnchantment(Enchantments.SMITE, 50);
			EnchSwordDetriminium.addEnchantment(Enchantments.UNBREAKING, 50);
			
			EnchPickDetriminium.addEnchantment(Enchantments.EFFICIENCY, 50);
			EnchPickDetriminium.addEnchantment(Enchantments.FORTUNE, 50);
			EnchPickDetriminium.addEnchantment(Enchantments.UNBREAKING, 50);

			EnchShovelDetriminium.addEnchantment(Enchantments.EFFICIENCY, 50);
			EnchShovelDetriminium.addEnchantment(Enchantments.FORTUNE, 50);
			EnchShovelDetriminium.addEnchantment(Enchantments.UNBREAKING, 50);

			EnchAxeDetriminium.addEnchantment(Enchantments.EFFICIENCY, 50);
			EnchAxeDetriminium.addEnchantment(Enchantments.FORTUNE, 50);
			EnchAxeDetriminium.addEnchantment(Enchantments.UNBREAKING, 50);
			EnchAxeDetriminium.addEnchantment(Enchantments.SHARPNESS, 50);

			GameRegistry.addShapedRecipe(new ResourceLocation("mores:esde_sword"), new ResourceLocation("custom_recipes"), EnchSwordDetriminium, new Object[]{" I ", " I ", " S ", 'I', "ingotDetriminium", 'S', Items.STICK});
			GameRegistry.addShapedRecipe(new ResourceLocation("mores:esde_pick"), new ResourceLocation("custom_recipes"), EnchPickDetriminium, new Object[]{"III", " S ", " S ", 'I', "ingotDetriminium", 'S', Items.STICK});
			GameRegistry.addShapedRecipe(new ResourceLocation("mores:esde_shovel"), new ResourceLocation("custom_recipes"), EnchShovelDetriminium, new Object[]{" I ", " S ", " S ", 'I', "ingotDetriminium", 'S', Items.STICK});
			GameRegistry.addShapedRecipe(new ResourceLocation("mores:esde_axe"), new ResourceLocation("custom_recipes"), EnchAxeDetriminium, new Object[]{" II", " SI", " S ", 'I', "ingotDetriminium", 'S', Items.STICK});
		}

	}
}
