package com.irar.mores.handlers;


import java.util.ArrayList;

import com.irar.mores.items.AlloyArmor;
import com.irar.mores.items.ItemIngot;
import com.irar.mores.items.MtlAxe;
import com.irar.mores.items.MtlPickaxe;
import com.irar.mores.items.MtlShovel;
import com.irar.mores.items.MtlSword;

import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.client.renderer.color.IItemColor;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ItemHandler {
	
	public static ArrayList<Item> allItems = new ArrayList<Item>();
	
	public static Item PhantomShard;
	public static Item BlackHoleFragment;
	public static Item BlackHoleShard;
	public static Item BydoomIngot;
	public static Item AuduIngot;
	public static Item AryxiIngot;
	public static Item AtaruIngot;
	public static Item UokuwixasiIngot;
	public static Item AikarIngot;
	public static Item AociIngot;
	public static Item DuxireteIngot;
	public static Item IrineIngot;
	public static Item JosawrilineIngot;
	public static Item MurolIngot;
	public static Item OdeznumIngot;
	public static Item OiviIngot;
	public static Item OivywonIngot;
	public static Item PetuxoIngot;
	public static Item RoIngot;
	public static Item SusimenIngot;
	public static Item UamafIngot;
	public static Item VodriciteIngot;
	public static Item VukaniteIngot;
	public static Item ZanineIngot;
	public static Item ZawiumIngot;
	public static Item IsaxiwukouIngot;
	public static Item EninazIngot;
	public static Item EniriIngot;
	public static Item IvioIngot;
	public static Item EterixudIngot;
	public static Item NowyvioIngot;

	public static Item AurineDust;
	public static Item AyzaniteDust;
	public static Item DraxateDust;
	public static Item EukavoyntDust;
	public static Item IturiteDust;
	public static Item NodemiteDust;
	public static Item SiveniumDust;
	
	public static Item BydoomDust;
	public static Item AuduDust;
	public static Item AryxiDust;
	public static Item AtaruDust;
	public static Item UokuwixasiDust;
	public static Item AikarDust;
	public static Item AociDust;
	public static Item DuxireteDust;
	public static Item IrineDust;
	public static Item JosawrilineDust;
	public static Item MurolDust;
	public static Item OdeznumDust;
	public static Item OiviDust;
	public static Item OivywonDust;
	public static Item PetuxoDust;
	public static Item RoDust;
	public static Item SusimenDust;
	public static Item UamafDust;
	public static Item VodriciteDust;
	public static Item VukaniteDust;
	public static Item ZanineDust;
	public static Item ZawiumDust;

	public static Item BydoomSword;
	public static Item AuduSword;
	public static Item AryxiSword;
	public static Item UokuwixasiSword;
	public static Item AikarSword;
	public static Item AociSword;
	public static Item DuxireteSword;
	public static Item IrineSword;
	public static Item JosawrilineSword;
	public static Item MurolSword;
	public static Item OdeznumSword;
	public static Item OiviSword;
	public static Item OivywonSword;
	public static Item PetuxoSword;
	public static Item RoSword;
	public static Item SusimenSword;
	public static Item UamafSword;
	public static Item VodriciteSword;
	public static Item VukaniteSword;
	public static Item ZanineSword;
	public static Item ZawiumSword;
	public static Item IsaxiwukouSword;
	public static Item EninazSword;
	public static Item EniriSword;
	public static Item IvioSword;
	public static Item EterixudSword;
	public static Item NowyvioSword;

	public static Item BydoomPick;
	public static Item AuduPick;
	public static Item AryxiPick;
	public static Item UokuwixasiPick;
	public static Item AikarPick;
	public static Item AociPick;
	public static Item DuxiretePick;
	public static Item IrinePick;
	public static Item JosawrilinePick;
	public static Item MurolPick;
	public static Item OdeznumPick;
	public static Item OiviPick;
	public static Item OivywonPick;
	public static Item PetuxoPick;
	public static Item RoPick;
	public static Item SusimenPick;
	public static Item UamafPick;
	public static Item VodricitePick;
	public static Item VukanitePick;
	public static Item ZaninePick;
	public static Item ZawiumPick;
	public static Item IsaxiwukouPick;
	public static Item EninazPick;
	public static Item EniriPick;
	public static Item IvioPick;
	public static Item EterixudPick;
	public static Item NowyvioPick;

	public static Item BydoomShovel;
	public static Item AuduShovel;
	public static Item AryxiShovel;
	public static Item UokuwixasiShovel;
	public static Item AikarShovel;
	public static Item AociShovel;
	public static Item DuxireteShovel;
	public static Item IrineShovel;
	public static Item JosawrilineShovel;
	public static Item MurolShovel;
	public static Item OdeznumShovel;
	public static Item OiviShovel;
	public static Item OivywonShovel;
	public static Item PetuxoShovel;
	public static Item RoShovel;
	public static Item SusimenShovel;
	public static Item UamafShovel;
	public static Item VodriciteShovel;
	public static Item VukaniteShovel;
	public static Item ZanineShovel;
	public static Item ZawiumShovel;
	public static Item IsaxiwukouShovel;
	public static Item EninazShovel;
	public static Item EniriShovel;
	public static Item IvioShovel;
	public static Item EterixudShovel;
	public static Item NowyvioShovel;

	public static Item BydoomAxe;
	public static Item AuduAxe;
	public static Item AryxiAxe;
	public static Item UokuwixasiAxe;
	public static Item AikarAxe;
	public static Item AociAxe;
	public static Item DuxireteAxe;
	public static Item IrineAxe;
	public static Item JosawrilineAxe;
	public static Item MurolAxe;
	public static Item OdeznumAxe;
	public static Item OiviAxe;
	public static Item OivywonAxe;
	public static Item PetuxoAxe;
	public static Item RoAxe;
	public static Item SusimenAxe;
	public static Item UamafAxe;
	public static Item VodriciteAxe;
	public static Item VukaniteAxe;
	public static Item ZanineAxe;
	public static Item ZawiumAxe;
	public static Item IsaxiwukouAxe;
	public static Item EninazAxe;
	public static Item EniriAxe;
	public static Item IvioAxe;
	public static Item EterixudAxe;
	public static Item NowyvioAxe;
	
	public static Item DetriminiumSword;
	public static Item DetriminiumPick;
	public static Item DetriminiumShovel;
	public static Item DetriminiumAxe;
	
	public static Item AlloyIngot;
	public static Item AlloyPickaxe;
	public static Item AlloyShovel;
	public static Item AlloyAxe;
	public static Item AlloySword;
	public static Item AlloyBow;
	public static Item AlloyHelmet;
	public static Item AlloyChestplate;
	public static Item AlloyLeggings;
	public static Item AlloyBoots;
	
	public static void init(){
		PhantomShard = new ItemIngot("phantom_shard");
		BlackHoleFragment = new ItemIngot("black_hole_fragment");
		BlackHoleShard = new ItemIngot("black_hole_shard");
		BydoomIngot = new ItemIngot("bydoom_ingot", 140);
		AuduIngot = new ItemIngot("audu_ingot", 377);
		AryxiIngot = new ItemIngot("aryxi_ingot", 514);
		AtaruIngot = new ItemIngot("ataru_ingot");
		UokuwixasiIngot = new ItemIngot("uokuwixasi_ingot", 7);
		AikarIngot = new ItemIngot("aikar_ingot", 360);
		AociIngot = new ItemIngot("aoci_ingot", 306);
		DuxireteIngot = new ItemIngot("duxirete_ingot", 380);
		IrineIngot = new ItemIngot("irine_ingot", 137);
		JosawrilineIngot = new ItemIngot("josawriline_ingot", 497);
		MurolIngot = new ItemIngot("murol_ingot", 86);
		OdeznumIngot = new ItemIngot("odeznum_ingot", 81);
		OiviIngot = new ItemIngot("oivi_ingot", 157);
		OivywonIngot = new ItemIngot("oivywon_ingot", 737);
		PetuxoIngot = new ItemIngot("petuxo_ingot", 517);
		RoIngot = new ItemIngot("ro_ingot", 443);
		SusimenIngot = new ItemIngot("susimen_ingot", 301);
		UamafIngot = new ItemIngot("uamaf_ingot", 438);
		VodriciteIngot = new ItemIngot("vodricite_ingot", 78);
		VukaniteIngot = new ItemIngot("vukanite_ingot", 83);
		ZanineIngot = new ItemIngot("zanine_ingot", 66);
		ZawiumIngot = new ItemIngot("zawium_ingot", 61);
		IsaxiwukouIngot = new ItemIngot("isaxiwukou_ingot", true);
		EninazIngot = new ItemIngot("eninaz_ingot", true);
		EniriIngot = new ItemIngot("eniri_ingot", true);
		IvioIngot = new ItemIngot("ivio_ingot", true);
		EterixudIngot = new ItemIngot("eterixud_ingot", true);
		NowyvioIngot = new ItemIngot("nowyvio_ingot", true);

		AurineDust = new ItemIngot("aurine_dust");
		AyzaniteDust = new ItemIngot("ayzanite_dust");
		DraxateDust = new ItemIngot("draxate_dust");
		EukavoyntDust = new ItemIngot("eukavoynt_dust");
		IturiteDust = new ItemIngot("iturite_dust");
		NodemiteDust = new ItemIngot("nodemite_dust");
		SiveniumDust = new ItemIngot("sivenium_dust");

		BydoomDust = new ItemIngot("bydoom_dust");
		AuduDust = new ItemIngot("audu_dust");
		AryxiDust = new ItemIngot("aryxi_dust");
		AtaruDust = new ItemIngot("ataru_dust");
		UokuwixasiDust = new ItemIngot("uokuwixasi_dust");
		AikarDust = new ItemIngot("aikar_dust");
		AociDust = new ItemIngot("aoci_dust");
		DuxireteDust = new ItemIngot("duxirete_dust");
		IrineDust = new ItemIngot("irine_dust");
		JosawrilineDust = new ItemIngot("josawriline_dust");
		MurolDust = new ItemIngot("murol_dust");
		OdeznumDust = new ItemIngot("odeznum_dust");
		OiviDust = new ItemIngot("oivi_dust");
		OivywonDust = new ItemIngot("oivywon_dust");
		PetuxoDust = new ItemIngot("petuxo_dust");
		RoDust = new ItemIngot("ro_dust");
		SusimenDust = new ItemIngot("susimen_dust");
		UamafDust = new ItemIngot("uamaf_dust");
		VodriciteDust = new ItemIngot("vodricite_dust");
		VukaniteDust = new ItemIngot("vukanite_dust");
		ZanineDust = new ItemIngot("zanine_dust");
		ZawiumDust = new ItemIngot("zawium_dust");

		BydoomSword = new MtlSword("bydoom_sword", ToolMaterialHandler.BYDOOM);
		AuduSword = new MtlSword("audu_sword", ToolMaterialHandler.AUDU);
		AryxiSword = new MtlSword("aryxi_sword", ToolMaterialHandler.ARYXI);
		UokuwixasiSword = new MtlSword("uokuwixasi_sword", ToolMaterialHandler.UOKUWIXASI);
		AikarSword = new MtlSword("aikar_sword", ToolMaterialHandler.AIKAR);
		AociSword = new MtlSword("aoci_sword", ToolMaterialHandler.AOCI);
		DuxireteSword = new MtlSword("duxirete_sword", ToolMaterialHandler.DUXIRETE);
		IrineSword = new MtlSword("irine_sword", ToolMaterialHandler.IRINE);
		JosawrilineSword = new MtlSword("josawriline_sword", ToolMaterialHandler.JOSAWRILINE);
		MurolSword = new MtlSword("murol_sword", ToolMaterialHandler.MUROL);
		OdeznumSword = new MtlSword("odeznum_sword", ToolMaterialHandler.ODEZNUM);
		OiviSword = new MtlSword("oivi_sword", ToolMaterialHandler.OIVI);
		OivywonSword = new MtlSword("oivywon_sword", ToolMaterialHandler.OIVYWON);
		PetuxoSword = new MtlSword("petuxo_sword", ToolMaterialHandler.PETUXO);
		RoSword = new MtlSword("ro_sword", ToolMaterialHandler.RO);
		SusimenSword = new MtlSword("susimen_sword", ToolMaterialHandler.SUSIMEN);
		UamafSword = new MtlSword("uamaf_sword", ToolMaterialHandler.UAMAF);
		VodriciteSword = new MtlSword("vodricite_sword", ToolMaterialHandler.VODRICITE);
		VukaniteSword = new MtlSword("vukanite_sword", ToolMaterialHandler.VUKANITE);
		ZanineSword = new MtlSword("zanine_sword", ToolMaterialHandler.ZANINE);
		ZawiumSword = new MtlSword("zawium_sword", ToolMaterialHandler.ZAWIUM);
		IsaxiwukouSword = new MtlSword("isaxiwukou_sword", ToolMaterialHandler.ISAXIWUKOU);
		EninazSword = new MtlSword("eninaz_sword", ToolMaterialHandler.ENINAZ);
		EniriSword = new MtlSword("eniri_sword", ToolMaterialHandler.ENIRI);
		IvioSword = new MtlSword("ivio_sword", ToolMaterialHandler.IVIO);
		EterixudSword = new MtlSword("eterixud_sword", ToolMaterialHandler.ETERIXUD);
		NowyvioSword = new MtlSword("nowyvio_sword", ToolMaterialHandler.NOWYVIO);

		BydoomPick = new MtlPickaxe("bydoom_pickaxe", ToolMaterialHandler.BYDOOM);
		AuduPick = new MtlPickaxe("audu_pickaxe", ToolMaterialHandler.AUDU);
		AryxiPick = new MtlPickaxe("aryxi_pickaxe", ToolMaterialHandler.ARYXI);
		UokuwixasiPick = new MtlPickaxe("uokuwixasi_pickaxe", ToolMaterialHandler.UOKUWIXASI);
		AikarPick = new MtlPickaxe("aikar_pickaxe", ToolMaterialHandler.AIKAR);
		AociPick = new MtlPickaxe("aoci_pickaxe", ToolMaterialHandler.AOCI);
		DuxiretePick = new MtlPickaxe("duxirete_pickaxe", ToolMaterialHandler.DUXIRETE);
		IrinePick = new MtlPickaxe("irine_pickaxe", ToolMaterialHandler.IRINE);
		JosawrilinePick = new MtlPickaxe("josawriline_pickaxe", ToolMaterialHandler.JOSAWRILINE);
		MurolPick = new MtlPickaxe("murol_pickaxe", ToolMaterialHandler.MUROL);
		OdeznumPick = new MtlPickaxe("odeznum_pickaxe", ToolMaterialHandler.ODEZNUM);
		OiviPick = new MtlPickaxe("oivi_pickaxe", ToolMaterialHandler.OIVI);
		OivywonPick = new MtlPickaxe("oivywon_pickaxe", ToolMaterialHandler.OIVYWON);
		PetuxoPick = new MtlPickaxe("petuxo_pickaxe", ToolMaterialHandler.PETUXO);
		RoPick = new MtlPickaxe("ro_pickaxe", ToolMaterialHandler.RO);
		SusimenPick = new MtlPickaxe("susimen_pickaxe", ToolMaterialHandler.SUSIMEN);
		UamafPick = new MtlPickaxe("uamaf_pickaxe", ToolMaterialHandler.UAMAF);
		VodricitePick = new MtlPickaxe("vodricite_pickaxe", ToolMaterialHandler.VODRICITE);
		VukanitePick = new MtlPickaxe("vukanite_pickaxe", ToolMaterialHandler.VUKANITE);
		ZaninePick = new MtlPickaxe("zanine_pickaxe", ToolMaterialHandler.ZANINE);
		ZawiumPick = new MtlPickaxe("zawium_pickaxe", ToolMaterialHandler.ZAWIUM);
		IsaxiwukouPick = new MtlPickaxe("isaxiwukou_pickaxe", ToolMaterialHandler.ISAXIWUKOU);
		EninazPick = new MtlPickaxe("eninaz_pickaxe", ToolMaterialHandler.ENINAZ);
		EniriPick = new MtlPickaxe("eniri_pickaxe", ToolMaterialHandler.ENIRI);
		IvioPick = new MtlPickaxe("ivio_pickaxe", ToolMaterialHandler.IVIO);
		EterixudPick = new MtlPickaxe("eterixud_pickaxe", ToolMaterialHandler.ETERIXUD);
		NowyvioPick = new MtlPickaxe("nowyvio_pickaxe", ToolMaterialHandler.NOWYVIO);

		BydoomShovel = new MtlShovel("bydoom_shovel", ToolMaterialHandler.BYDOOM);
		AuduShovel = new MtlShovel("audu_shovel", ToolMaterialHandler.AUDU);
		AryxiShovel = new MtlShovel("aryxi_shovel", ToolMaterialHandler.ARYXI);
		UokuwixasiShovel = new MtlShovel("uokuwixasi_shovel", ToolMaterialHandler.UOKUWIXASI);
		AikarShovel = new MtlShovel("aikar_shovel", ToolMaterialHandler.AIKAR);
		AociShovel = new MtlShovel("aoci_shovel", ToolMaterialHandler.AOCI);
		DuxireteShovel = new MtlShovel("duxirete_shovel", ToolMaterialHandler.DUXIRETE);
		IrineShovel = new MtlShovel("irine_shovel", ToolMaterialHandler.IRINE);
		JosawrilineShovel = new MtlShovel("josawriline_shovel", ToolMaterialHandler.JOSAWRILINE);
		MurolShovel = new MtlShovel("murol_shovel", ToolMaterialHandler.MUROL);
		OdeznumShovel = new MtlShovel("odeznum_shovel", ToolMaterialHandler.ODEZNUM);
		OiviShovel = new MtlShovel("oivi_shovel", ToolMaterialHandler.OIVI);
		OivywonShovel = new MtlShovel("oivywon_shovel", ToolMaterialHandler.OIVYWON);
		PetuxoShovel = new MtlShovel("petuxo_shovel", ToolMaterialHandler.PETUXO);
		RoShovel = new MtlShovel("ro_shovel", ToolMaterialHandler.RO);
		SusimenShovel = new MtlShovel("susimen_shovel", ToolMaterialHandler.SUSIMEN);
		UamafShovel = new MtlShovel("uamaf_shovel", ToolMaterialHandler.UAMAF);
		VodriciteShovel = new MtlShovel("vodricite_shovel", ToolMaterialHandler.VODRICITE);
		VukaniteShovel = new MtlShovel("vukanite_shovel", ToolMaterialHandler.VUKANITE);
		ZanineShovel = new MtlShovel("zanine_shovel", ToolMaterialHandler.ZANINE);
		ZawiumShovel = new MtlShovel("zawium_shovel", ToolMaterialHandler.ZAWIUM);
		IsaxiwukouShovel = new MtlShovel("isaxiwukou_shovel", ToolMaterialHandler.ISAXIWUKOU);
		EninazShovel = new MtlShovel("eninaz_shovel", ToolMaterialHandler.ENINAZ);
		EniriShovel = new MtlShovel("eniri_shovel", ToolMaterialHandler.ENIRI);
		IvioShovel = new MtlShovel("ivio_shovel", ToolMaterialHandler.IVIO);
		EterixudShovel = new MtlShovel("eterixud_shovel", ToolMaterialHandler.ETERIXUD);
		NowyvioShovel = new MtlShovel("nowyvio_shovel", ToolMaterialHandler.NOWYVIO);

		BydoomAxe = new MtlAxe("bydoom_axe", ToolMaterialHandler.BYDOOM);
		AuduAxe = new MtlAxe("audu_axe", ToolMaterialHandler.AUDU);
		AryxiAxe = new MtlAxe("aryxi_axe", ToolMaterialHandler.ARYXI);
		UokuwixasiAxe = new MtlAxe("uokuwixasi_axe", ToolMaterialHandler.UOKUWIXASI);
		AikarAxe = new MtlAxe("aikar_axe", ToolMaterialHandler.AIKAR);
		AociAxe = new MtlAxe("aoci_axe", ToolMaterialHandler.AOCI);
		DuxireteAxe = new MtlAxe("duxirete_axe", ToolMaterialHandler.DUXIRETE);
		IrineAxe = new MtlAxe("irine_axe", ToolMaterialHandler.IRINE);
		JosawrilineAxe = new MtlAxe("josawriline_axe", ToolMaterialHandler.JOSAWRILINE);
		MurolAxe = new MtlAxe("murol_axe", ToolMaterialHandler.MUROL);
		OdeznumAxe = new MtlAxe("odeznum_axe", ToolMaterialHandler.ODEZNUM);
		OiviAxe = new MtlAxe("oivi_axe", ToolMaterialHandler.OIVI);
		OivywonAxe = new MtlAxe("oivywon_axe", ToolMaterialHandler.OIVYWON);
		PetuxoAxe = new MtlAxe("petuxo_axe", ToolMaterialHandler.PETUXO);
		RoAxe = new MtlAxe("ro_axe", ToolMaterialHandler.RO);
		SusimenAxe = new MtlAxe("susimen_axe", ToolMaterialHandler.SUSIMEN);
		UamafAxe = new MtlAxe("uamaf_axe", ToolMaterialHandler.UAMAF);
		VodriciteAxe = new MtlAxe("vodricite_axe", ToolMaterialHandler.VODRICITE);
		VukaniteAxe = new MtlAxe("vukanite_axe", ToolMaterialHandler.VUKANITE);
		ZanineAxe = new MtlAxe("zanine_axe", ToolMaterialHandler.ZANINE);
		ZawiumAxe = new MtlAxe("zawium_axe", ToolMaterialHandler.ZAWIUM);
		IsaxiwukouAxe = new MtlAxe("isaxiwukou_axe", ToolMaterialHandler.ISAXIWUKOU);
		EninazAxe = new MtlAxe("eninaz_axe", ToolMaterialHandler.ENINAZ);
		EniriAxe = new MtlAxe("eniri_axe", ToolMaterialHandler.ENIRI);
		IvioAxe = new MtlAxe("ivio_axe", ToolMaterialHandler.IVIO);
		EterixudAxe = new MtlAxe("eterixud_axe", ToolMaterialHandler.ETERIXUD);
		NowyvioAxe = new MtlAxe("nowyvio_axe", ToolMaterialHandler.NOWYVIO);
		
		AlloyIngot = new com.irar.mores.items.AlloyIngot("alloy_ingot");
		AlloyPickaxe = new com.irar.mores.items.AlloyPickaxe("alloy_pickaxe");
		AlloyShovel = new com.irar.mores.items.AlloyShovel("alloy_shovel");
		AlloyAxe = new com.irar.mores.items.AlloyAxe("alloy_axe");
		AlloySword = new com.irar.mores.items.AlloySword("alloy_sword");
		AlloyBow = new com.irar.mores.items.AlloyBow("alloy_bow");
		AlloyHelmet = new AlloyArmor("alloy_helmet", EntityEquipmentSlot.HEAD, "Helmet");
		AlloyChestplate = new AlloyArmor("alloy_chestplate", EntityEquipmentSlot.CHEST, "Chestplate");
		AlloyLeggings = new AlloyArmor("alloy_leggings", EntityEquipmentSlot.LEGS, "Leggings");
		AlloyBoots = new AlloyArmor("alloy_boots", EntityEquipmentSlot.FEET, "Boots");
		
		allItems.add(PhantomShard);
		 allItems.add(BlackHoleFragment);
		 allItems.add(BlackHoleShard);
		 allItems.add(BydoomIngot);
		 allItems.add(AuduIngot);
		 allItems.add(AryxiIngot);
		 allItems.add(AtaruIngot);
		 allItems.add(UokuwixasiIngot);
		 allItems.add(AikarIngot);
		 allItems.add(AociIngot);
		 allItems.add(DuxireteIngot);
		 allItems.add(IrineIngot);
		 allItems.add(JosawrilineIngot);
		 allItems.add(MurolIngot);
		 allItems.add(OdeznumIngot);
		 allItems.add(OiviIngot);
		 allItems.add(OivywonIngot);
		 allItems.add(PetuxoIngot);
		 allItems.add(RoIngot);
		 allItems.add(SusimenIngot);
		 allItems.add(UamafIngot);
		 allItems.add(VodriciteIngot);
		 allItems.add(VukaniteIngot);
		 allItems.add(ZanineIngot);
		 allItems.add(ZawiumIngot);
		 allItems.add(IsaxiwukouIngot);
		 allItems.add(EninazIngot);
		 allItems.add(EniriIngot);
		 allItems.add(IvioIngot);
		 allItems.add(EterixudIngot);
		 allItems.add(NowyvioIngot);

		 allItems.add(AurineDust);
		 allItems.add(AyzaniteDust);
		 allItems.add(DraxateDust);
		 allItems.add(EukavoyntDust);
		 allItems.add(IturiteDust);
		 allItems.add(NodemiteDust);
		 allItems.add(SiveniumDust);
		 
		 allItems.add(BydoomDust);
		 allItems.add(AuduDust);
		 allItems.add(AryxiDust);
		 allItems.add(AtaruDust);
		 allItems.add(UokuwixasiDust);
		 allItems.add(AikarDust);
		 allItems.add(AociDust);
		 allItems.add(DuxireteDust);
		 allItems.add(IrineDust);
		 allItems.add(JosawrilineDust);
		 allItems.add(MurolDust);
		 allItems.add(OdeznumDust);
		 allItems.add(OiviDust);
		 allItems.add(OivywonDust);
		 allItems.add(PetuxoDust);
		 allItems.add(RoDust);
		 allItems.add(SusimenDust);
		 allItems.add(UamafDust);
		 allItems.add(VodriciteDust);
		 allItems.add(VukaniteDust);
		 allItems.add(ZanineDust);
		 allItems.add(ZawiumDust);

		 allItems.add(BydoomSword);
		 allItems.add(AuduSword);
		 allItems.add(AryxiSword);
		 allItems.add(UokuwixasiSword);
		 allItems.add(AikarSword);
		 allItems.add(AociSword);
		 allItems.add(DuxireteSword);
		 allItems.add(IrineSword);
		 allItems.add(JosawrilineSword);
		 allItems.add(MurolSword);
		 allItems.add(OdeznumSword);
		 allItems.add(OiviSword);
		 allItems.add(OivywonSword);
		 allItems.add(PetuxoSword);
		 allItems.add(RoSword);
		 allItems.add(SusimenSword);
		 allItems.add(UamafSword);
		 allItems.add(VodriciteSword);
		 allItems.add(VukaniteSword);
		 allItems.add(ZanineSword);
		 allItems.add(ZawiumSword);
		 allItems.add(IsaxiwukouSword);
		 allItems.add(EninazSword);
		 allItems.add(EniriSword);
		 allItems.add(IvioSword);
		 allItems.add(EterixudSword);
		 allItems.add(NowyvioSword);

		 allItems.add(BydoomPick);
		 allItems.add(AuduPick);
		 allItems.add(AryxiPick);
		 allItems.add(UokuwixasiPick);
		 allItems.add(AikarPick);
		 allItems.add(AociPick);
		 allItems.add(DuxiretePick);
		 allItems.add(IrinePick);
		 allItems.add(JosawrilinePick);
		 allItems.add(MurolPick);
		 allItems.add(OdeznumPick);
		 allItems.add(OiviPick);
		 allItems.add(OivywonPick);
		 allItems.add(PetuxoPick);
		 allItems.add(RoPick);
		 allItems.add(SusimenPick);
		 allItems.add(UamafPick);
		 allItems.add(VodricitePick);
		 allItems.add(VukanitePick);
		 allItems.add(ZaninePick);
		 allItems.add(ZawiumPick);
		 allItems.add(IsaxiwukouPick);
		 allItems.add(EninazPick);
		 allItems.add(EniriPick);
		 allItems.add(IvioPick);
		 allItems.add(EterixudPick);
		 allItems.add(NowyvioPick);

		 allItems.add(BydoomShovel);
		 allItems.add(AuduShovel);
		 allItems.add(AryxiShovel);
		 allItems.add(UokuwixasiShovel);
		 allItems.add(AikarShovel);
		 allItems.add(AociShovel);
		 allItems.add(DuxireteShovel);
		 allItems.add(IrineShovel);
		 allItems.add(JosawrilineShovel);
		 allItems.add(MurolShovel);
		 allItems.add(OdeznumShovel);
		 allItems.add(OiviShovel);
		 allItems.add(OivywonShovel);
		 allItems.add(PetuxoShovel);
		 allItems.add(RoShovel);
		 allItems.add(SusimenShovel);
		 allItems.add(UamafShovel);
		 allItems.add(VodriciteShovel);
		 allItems.add(VukaniteShovel);
		 allItems.add(ZanineShovel);
		 allItems.add(ZawiumShovel);
		 allItems.add(IsaxiwukouShovel);
		 allItems.add(EninazShovel);
		 allItems.add(EniriShovel);
		 allItems.add(IvioShovel);
		 allItems.add(EterixudShovel);
		 allItems.add(NowyvioShovel);

		 allItems.add(BydoomAxe);
		 allItems.add(AuduAxe);
		 allItems.add(AryxiAxe);
		 allItems.add(UokuwixasiAxe);
		 allItems.add(AikarAxe);
		 allItems.add(AociAxe);
		 allItems.add(DuxireteAxe);
		 allItems.add(IrineAxe);
		 allItems.add(JosawrilineAxe);
		 allItems.add(MurolAxe);
		 allItems.add(OdeznumAxe);
		 allItems.add(OiviAxe);
		 allItems.add(OivywonAxe);
		 allItems.add(PetuxoAxe);
		 allItems.add(RoAxe);
		 allItems.add(SusimenAxe);
		 allItems.add(UamafAxe);
		 allItems.add(VodriciteAxe);
		 allItems.add(VukaniteAxe);
		 allItems.add(ZanineAxe);
		 allItems.add(ZawiumAxe);
		 allItems.add(IsaxiwukouAxe);
		 allItems.add(EninazAxe);
		 allItems.add(EniriAxe);
		 allItems.add(IvioAxe);
		 allItems.add(EterixudAxe);
		 allItems.add(NowyvioAxe);
		 
		 allItems.add(AlloyIngot);
		 allItems.add(AlloyPickaxe);
		 allItems.add(AlloyShovel);
		 allItems.add(AlloyAxe);
		 allItems.add(AlloySword);
		 allItems.add(AlloyBow);
		 allItems.add(AlloyHelmet);
		 allItems.add(AlloyChestplate);
		 allItems.add(AlloyLeggings);
		 allItems.add(AlloyBoots);
		 
		 if(Loader.isModLoaded("iron")){
			 DetriminiumSword = new MtlSword("detriminium_sword", ToolMaterialHandler.DETRIMINIUM);
			 DetriminiumPick = new MtlPickaxe("detriminium_pickaxe", ToolMaterialHandler.DETRIMINIUM);
			 DetriminiumShovel = new MtlShovel("detriminium_shovel", ToolMaterialHandler.DETRIMINIUM);
			 DetriminiumAxe = new MtlAxe("detriminium_axe", ToolMaterialHandler.DETRIMINIUM);
			 allItems.add(DetriminiumSword);
			 allItems.add(DetriminiumPick);
			 allItems.add(DetriminiumShovel);
			 allItems.add(DetriminiumAxe);
		 }
		 
	}
	public static void register(){
		for(int i = 0; i < allItems.size(); i++){
			 ForgeRegistries.ITEMS.register(allItems.get(i));
		}
	}
	
	public static void registerRenders(){
		for(int i = 0; i < allItems.size(); i++){
			registerRender(allItems.get(i));
		}
	}
	
	public static void registerRender(Item item){
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
		
		if(item.getHasSubtypes()) {
			Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 1, new ModelResourceLocation(item.getRegistryName(), "inventory"));
		}
		
		if(item instanceof IItemColor) {
			Minecraft.getMinecraft().getItemColors().registerItemColorHandler((IItemColor) item, item);
		}
	}


	
}
